bert:
  arch: large
  batch_size: 2
  num_iterations: 3000
  request_rate: 25
mobilenet_v2:
  arch: mobilenet_v2
  batch_size: 16
  num_iterations: 9200
  request_rate: 200
models:
  model0:
    mode: eval
    name: resnet101
  model1:
    mode: eval
    name: bert
policy: MPS
resnet101:
  arch: resnet101
  batch_size: 8
  num_iterations: 5000
  request_rate: 100
resnet50:
  arch: resnet50
  batch_size: 8
  num_iterations: 9200
  request_rate: 200
shared_config:
  distribution: poisson
  pin_memory: true
  seed: 42
  trace_path: ./inter_arrival_times.json
